### ISSUE TITLE
Error handling soft clipping

### ISSUE THREAD

**Issue by GoogleCodeExporter** [andrewparkermorgan/lapels#3]
```

I am attempting to run lapels on STAR output (this is RNA-seq data). It appears 
to die on an assert when soft clipping is encountered.  The soft clip element 
of the cigar I believe is not handled properly.

assert nRegions == len(rseq.cigar)


Here is the traceback:

Traceback (most recent call last):
  File "/usr/local/bin/pylapels", line 5, in <module>
    pkg_resources.run_script('lapels==1.0.6', 'pylapels')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 499, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1235, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/lapels-1.0.6-py2.7.egg/EGG-INFO/scripts/pylapels", line 373, in <module>
    run()
  File "/usr/local/lib/python2.7/dist-packages/lapels-1.0.6-py2.7.egg/EGG-INFO/scripts/pylapels", line 316, in run
    annotate(args.bamin_fn, args.mod_fn, mergePool, chrom)
  File "/usr/local/lib/python2.7/dist-packages/lapels-1.0.6-py2.7.egg/EGG-INFO/scripts/pylapels", line 179, in annotate
    ret = a.execute()
  File "/usr/local/lib/python2.7/dist-packages/lapels-1.0.6-py2.7.egg/lapels/annotator.py", line 399, in execute
    assert nRegions == len(rseq.cigar)
AssertionError



I am running on Ubuntu 12.04 32 bit.  Lapels was intalled using easy-install.
```

Original issue reported on code.google.com by `lisle.m...@gmail.com` on 12 Jan 2015 at 4:09

**Comment by shunping** [comment]
It has been fixed in v1.1.1. Please refer to https://github.com/shunping/lapels/ .
